name: Shellcheck

on:
  pull_request:
    paths:
      - '**.sh'
  push:
    branches:
      - main
    paths:
      - '**.sh'

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'
        env:
          SHELLCHECK_OPTS: --shell bash